### PR TITLE
Render time information sensitive to the original time zone of the event.

### LINKED ISSUE #260: Time column ignores daylight saving time
# Environment
- Since commit c10d5d147edb63f34245a0198c646f3274df9a91
- Affected versions: [v.1.42.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.42.0)
- System time: 30.03.2020 (summer time)
- Product flavor: `ccc36C3`
- Example lecture: The "Opening ceremony" in room "Ada" which starts at 11:00am

# How to reproduce
1. Install and start the 36C3 app
2. Take a look at the time column next to the example lecture.

# Observed behavior
- The "Opening ceremony" is shown at the time column entry `12:00`.
36c3-bad

# Expected behavior
- The "Opening ceremony" is shown at the time column entry `11:00`.
36c3-good

# Hints
- The time columns shows the correct behavior when the system time of the device is set to 28.03.2020 (winter time). Summer time started at 29.03.2020 at 02:00am.
- The issue is caused by a new implementation of the date/time stack which makes the time column component behave sensitive to winner resp. summer time. See commit message in c10d5d147edb63f34245a0198c646f3274df9a91.

# Related
- [Issue #69: Event time or device time](https://github.com/EventFahrplan/EventFahrplan/issues/69)
- [Issue #245: Centralize date handling](https://github.com/EventFahrplan/EventFahrplan/pull/245)

### PR DESCRIPTION
**Pull request by johnjohndoe**
# Description
+ The **original time zone offset** of a session is parsed, stored and used to render its time correctly - at any point in time. That means, the device system time might be set to **before, at or after** the time of the event. Further, the time zone of the device does not need to match the time zone of the event.
+ **Fallback:** If the time zone offset is not provided then the app falls back to using the current **time zone offset of the device** in lack of better knowledge.
+ Rendering time information according to the time zone of the device is **not** implemented yet. It will be implemented later.
+ Test time rendering in **different device time zones**.

## This commit affects the rendering of:
+ the time text column (hours, minutes)
+ the time information in the top bar in the details screen
+ the time information of an alarm item in the alarms screen
+ the time information of the session items in the favorites screen
+ the time information of the session items in the changes screen

## This commit does not affect the scrolling behavior:
+ Scrolling to the current time if the selected event day matches the current day
+ Scrolling to the associated session (time) when tapping an alarm notification
  + Here are still issues which will be addressed in a follow-up pull request

# Successfully tested on
with `rc3` flavor, `debug` build
- :heavy_check_mark: Pixel 2 device, Android 10 (API 29)

# Related
- [Issue #69: Event time or device time](https://github.com/EventFahrplan/EventFahrplan/issues/69)
- [Pull request #245: Centralize date handling](https://github.com/EventFahrplan/EventFahrplan/pull/245)
- [Issue #260: Time column ignores daylight saving time](https://github.com/EventFahrplan/EventFahrplan/issues/260)

# Travis CI
- Please ignore the build. CI is currently out of service. :no_entry: 

---

Resolves #260

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@ideadapt, @a-tze I found the time to implement the "date/time rendering" with respect to the original time zone offset of the event/sessions. You are welcome to comment on the implementation and point out any shortcomings - if your time allows.

File: commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/DateParser.kt [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+object DateParser {
+
+    /**
+     * Parses the given [text] and returns its date value represented in milliseconds.
+     *
+     * Expects the [text] to be provided in [ISO_DATE_TIME][DateTimeFormatter.ISO_DATE_TIME]
+     * format (e.g. 2019-01-01T00:00:00Z).
+     */
+    fun parseDateTime(text: String): Long {
```
Comment (ideadapt) [inline commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/DateParser.kt:17]: I see that info.metadude.android.eventfahrplan.network.temporal.DateParser has very similar functionality. Why not extend / reuse it?
