### PR TITLE
Don't use MyApp.lectureList to populate EventDetailFragment

### LINKED ISSUE #204: IllegalStateException: Lecture list does not contain eventId
Crash report from different users:

- Sent: 17.12.2019 - 23.12.2019
- App version: [v.1.40.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.40.0), [v.1.41.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.41.0)
- Android version: 9, 10
- Device models: ONEPLUS A6013, ONE A2003, HMA-L29, moto g(7), Pixel 3

# Stacktrace
``` java
java.lang.IllegalStateException: Lecture list does not contain eventId: 1066, lecture:
    Lecture{changedTitle=false, changedSubtitle=false, changedRoom=false, 
    changedDay=true, changedTime=true, changedDuration=false, changedSpeakers=false, 
    changedRecordingOptOut=false, changedLanguage=false, changedTrack=false, 
    changedIsNew=false, changedIsCanceled=false}

at nerd.tuxmobil.fahrplan.congress.details.EventDetailFragment.eventIdToLecture(EventDetailFragment.java:342)
at nerd.tuxmobil.fahrplan.congress.details.EventDetailFragment.onViewCreated(EventDetailFragment.java:153)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
```

# Log
``` java
0 D: Writing unhandled exception to: /data/user/0/info.metadude.android.congress.schedule/files/1.40.0-1576593187349.tracedroid
1 D: 1066: Lecture{changedTitle=false, changedSubtitle=false, changedRoom=false, changedDay=true, changedTime=true, changedDuration=false, changedSpeakers=false, changedRecordingOptOut=false, changedLanguage=false, changedTrack=false, changedIsNew=false, changedIsCanceled=false}
2 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag="5df8df79-fe519", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=awk; chaos-west 1.0; open-infra 6; wikipaka 0.4; chaoszone 0.2; lightning Yttrium; wiki 2019-12-17 15:00)
3 D: viewDay(false)
4 D: meta.getNumDays() = 4
5 D: MyApp.task_running = NONE
6 D: lectureId = null
7 D: MyApp.lectureList contains 135 items.
8 D: onResume
9 D: Add alarm for lecture: 739, alarmTimesIndex: 5
10 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag="5df8daca-fe4e1", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=awk; chaos-west 1.0; open-infra 6; wikipaka 0.4; chaoszone 0.2; lightning Yttrium; wiki 2019-12-17 14:20)
11 D: viewDay(false)
12 D: meta.getNumDays() = 4
13 D: MyApp.task_running = NONE
14 D: lectureId = null
15 D: MyApp.lectureList contains 164 items.
16 D: onResume
17 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag="5df8b098-fbf4c", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=awk; chaos-west 1.0; open-infra 5; wikipaka 0.4; chaoszone 0.2; lightning Yttrium; wiki 2019-12-17 11:10)
18 D: viewDay(false)
19 D: meta.getNumDays() = 4
20 D: MyApp.task_running = NONE
21 D: lectureId = null
22 D: MyApp.lectureList contains 134 items.
23 D: onResume
24 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag="5df8b098-fbf4c", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=awk; chaos-west 1.0; open-infra 5; wikipaka 0.4; chaoszone 0.2; lightning Scandium; wiki 2019-12-16 18:20)
25 D: viewDay(false)
26 D: meta.getNumDays() = 4
27 D: MyApp.task_running = NONE
28 D: lectureId = null
29 D: MyApp.lectureList contains 129 items.
30 D: onResume
31 D: Fetching schedule already in progress.
32 D: Menu item: Refresh
33 D: MyApp.meta = Meta(dayChangeHour=0, dayChangeMinute=0, eTag="5df7c18e-fef64", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=awk; chaos-west 1.0; open-infra 5; wikipaka 0.4; chaoszone 0.2; lightning Scandium; wiki 2019-12-16 18:20)
34 D: viewDay(false)
35 D: meta.getNumDays() = 4
36 D: MyApp.task_running = NONE
37 D: lectureId = null
38 D: MyApp.lectureList = null
39 D: onResume
40 D: current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
```

# User report
> I was browsing a change report and the app fetched a new one one in the background (i guess). When I clicked on one of the changes the app crashed and showed me changes without the one I clicked on.

# Related
- [Issue #103: IllegalStateException: Lecture list does not contain eventId](https://github.com/EventFahrplan/EventFahrplan/issues/103)

### PR DESCRIPTION
**Pull request by cketti**
### Description
Don't use the outdated `MyApp.lectureList` mechanism to populate `EventDetailFragment`'s UI.

### Before
`MyApp.lectureList` was populated using the `day` argument of `EventDetailFragment`. This lead to the lecture not being found by `eventIdToLecture()` when the event was updated and moved to another day while the change list was displayed.

### After
We fetch the lecture from the database using `AppRepository.readLectureByLectureId()`, bypassing the `MyApp.lectureList` mechanism.
The `MyApp.lectureList` mechanism is populating `Lecture.isHighlight` and `Lecture.hasAlarm`.  `AppRepository.readLectureByLectureId()` was therefore updated to also provide this functionality.

I was able to reproduce #204 using the provided schedule files. This PR fixes that issue.

Resolves #204

### CODE REVIEW

File: database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/HighlightsDatabaseRepository.kt [hunk 1]
```diff
@@ -56,4 +56,32 @@ class HighlightsDatabaseRepository(
...
+            if (cursor.moveToFirst()) {
+                val highlightState = cursor.getInt(HIGHLIGHT)
+                val isHighlighted = highlightState == HIGHLIGHT_STATE_ON
+                Highlight(eventId, isHighlighted)
+            } else {
+                null
+            }
+        }
+
+        sqLiteOpenHelper.close()
```
Comment (johnjohndoe) [inline database/src/main/java/info/metadude/android/eventfahrplan/database/repositories/HighlightsDatabaseRepository.kt]: I am missing `database.close()` here similar to the `query()` method above.

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt [hunk 2]
```diff
@@ -279,8 +279,21 @@ object AppRepository {
         highlightsDatabaseRepository.insert(values, lecture.lectureId)
     }
 
-    fun readLectureByLectureId(lectureId: String) =
-            lecturesDatabaseRepository.queryLectureByLectureId(lectureId).first().toLectureAppModel()
+    fun readLectureByLectureId(lectureId: String): Lecture {
+        val lecture = lecturesDatabaseRepository.queryLectureByLectureId(lectureId).toLectureAppModel()
+
+        val highlight = highlightsDatabaseRepository.queryByEventId(lectureId.toInt())
```
Comment (cketti) [inline app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt]: Read highlights because it's also done here: https://github.com/EventFahrplan/EventFahrplan/blob/0cd0820a8c12d832a8b2e57d937d72da2a4110c0/app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt#L241-L249

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt [hunk 3]
```diff
@@ -279,8 +279,21 @@ object AppRepository {
...
+        if (highlight != null) {
+            lecture.highlight = highlight.isHighlight
+        }
+
+        val alarms = alarmsDatabaseRepository.query(lectureId)
```
Comment (cketti) [inline app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/AppRepository.kt]: Read alarms because `FahrplanFragment.loadLectureList()` is doing it here:
https://github.com/EventFahrplan/EventFahrplan/blob/0cd0820a8c12d832a8b2e57d937d72da2a4110c0/app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java#L771

**Comment by johnjohndoe** [comment]
Thanks a lot for your work. Let's hope we can kill a :bug: here at Congress. :crossed_fingers:
