### PR TITLE
Correct the JSON output for the share action

### LINKED ISSUE #596: Share to JSON seems to be buggy? Sharing wrong information.
Hi.

I was fiddling around with sharing to HTTP Requests and stumbled upon various fields in the json not ligning up in name and content.

Looking at: 

https://github.com/EventFahrplan/EventFahrplan/blob/9abc55d497833b60e6e1aed06ffd0ff8b4408a4e/app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt#L35-L41

I am suspecting a copy & paste error snuck in. Hopefully I'm on the right track and it's an easy fix.

Cheers.

### PR DESCRIPTION
**Pull request by IsoLinearCHiP**
# Acknowledgments
Please check the following boxes with an `x` if they apply:
* [x] I have read the recent version of the [contribution guide](
  https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before creating this pull request.
* [ ] I have checked a few other pull requests to see how they are written.
* [ ] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that EventFahrplan is mostly developed by one person in their unpaid spare time.
* [x] I can help myself to get this feature implemented or know someone who wants to do it.

# Description
- Intended to fix the bug I reported in #596.
- Shift the fields to the correct values
- Add missing field date

# Before
The JSON output of the share function had values in the wrong fields for some fields and was missing the date field.

# After
Fixed the output.

Resolves #596

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@IsoLinearCHiP Thank you for this pull request. I should have time to have a look by the end of the week.

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt [hunk 1]
```diff
@@ -33,10 +33,11 @@ data class SessionExport(
...
-            lang = session.abstractt,
-            abstract = session.description,
-            description = session.links,
-            links = session.date
+            type = session.type,
+            lang = session.lang,
+            abstract = session.abstractt,
+            description = session.description,
+            links = session.links,
+            date = session.date
```
Comment (johnjohndoe) [inline app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt:41]: Do we need `date` at all? Chaosflix does not care as far as I know. Sadly, I cannot verify it either. It seems the import function in Chaosflix no longer works on recent Android version.

If you think a date/time information should be there I recommend picking `dateUtc` instead like this:

``` kotlin
date = Moment.ofEpochMilli(session.dateUTC).toString()
```

**Review by johnjohndoe — CHANGES_REQUESTED** [review]
Can you please add the following reference in your commit message body so its easier to find the related commit in the Git history?

```
+ Broken since: c90b63942c0a13120a70cee8c4ef8be0fa29ea80
```

**Comment by IsoLinearCHiP** [comment]
> Can you please add the following reference in your commit message body so its easier to find the related commit in the Git history?
> 
> ```
> + Broken since: c90b63942c0a13120a70cee8c4ef8be0fa29ea80
> ```

Sorry, was busy, almost forgot about this. I've changed the commit message.

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt (hunk 1 above)
Comment (IsoLinearCHiP) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt:41]: Oh, ok. You suggested more changes.

I believe there shouldn't be any harm in having the date, if it doesn't break compatibility with the originally consuming app. I'd appreciate having access to it.

> Since the field has never been exported I would even rename it to `startsAt` resp. `starts_at` for the JSON export which is much clearer than `date`.

I am not quite sure where you want that inserted. The suggestion sounds good, I just don't know how to implemented it, as I have never used Kotlin before. Maybe changes at that level would be better done by someone who actually knows what they are doing. :rofl:

Comment (johnjohndoe) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt:41]: > I'd appreciate having access to it.

OK, then lets put it in.

It's not too hard. You basically have to replace this line:

``` kotlin
var date: String? = null
```

with:

``` kotlin
@Json(name = "starts_at")
var startsAt: String? = null,
```

and:

``` kotlin
date = session.date
```

with:

``` kotlin
startsAt = Moment.ofEpochMilli(session.dateUTC).toString()
```

Comment (IsoLinearCHiP) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/sharing/models/SessionExport.kt]: Ok, needed to figure out how to do imports, tests have passed, hope its the way you wanted it.

**Review by johnjohndoe — APPROVED** [review]
LGTM :dancers: Thanks for the effort!

**Comment by johnjohndoe** [comment]
@IsoLinearCHiP Can you please grant me either push permission to this branch or rebase it yourself onto the latest commit on my `master` branch? I can help with the Git commands if that is needed.

**Comment by IsoLinearCHiP** [comment]
@johnjohndoe Ill probably get to it this weekend, since I first need to fix a certain grub error you seem to have also encountered a few years ago, judging by the avatar on the on the askubuntu.com answer I just stumbled apon. Sometimes its scary how small the internet is :rofl:

**Comment by johnjohndoe** [comment]
Thanks for the notice. I hope your attempt to fix it turns out well. 🤞 Not a topic one likes to deal with too often.

**Review by johnjohndoe — APPROVED** [review]
