### PR TITLE
Fix scrolling to session when tapping session alarm notification.

### LINKED ISSUE #346: Tapping a session alarm notification scrolls the associated session out of view
# Environment
- App version: [v.1.47.0](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.47.0)
- Android version: all
- Branch: `master`
- Device: all

# How to reproduce
1. Install the 36C3 app.
2. Schedule an alarm for a session (memorize the session).
3. Swipe the main schedule view to another column and time.
4. Tap the session alarm notification which shows up in the status bar.
5. Tapping a schedule notification opens the app and scrolls to the correct room column.

# Observed behavior
- The relevant session is **not visible**. The room column view scrolls a bit too far down so that the session is **out of sight**.

# Expected behavior
- The relevant session is shown. The room column view positions the relevant session at the top of the room column.

# Hints
- Check behavior of edge cases such as elements at the top or bottom of a room column.

### PR DESCRIPTION
**Pull request by johnjohndoe**
# Description
- The start time minutes calculated for the session are in UTC.
- Before the vertical scroll position is calculated the minutes must be translated into the system time zone because this is used for the time line column and for positioning the session.
- Add unit tests for time zone offset calculation.

# Successfully tested on
with `ccc36c3` flavor, `debug` build
- :heavy_check_mark: Pixel 2 device, Android 10 (API 29)

Resolves #346.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@a-tze Do you want to review this?

**Comment by a-tze** [comment]
@johnjohndoe I'm not sure in which context this code will be called. It will work correctly if the context is "now", but calculating the offset from "Now" and maybe even using it in broader context is something that does not work (in fact I even had a bug like this in a 3rd party software last week and now have some cleanup to do).
The only way to get this correct is to calculate the offset again and again for each and every non-utc datetime that you encounter. I'll add another comment at the relevant place in the commit.

File: commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/Moment.kt [hunk 1]
```diff
@@ -108,12 +109,29 @@ class Moment private constructor(private val time: Instant) {
...
          */
         @JvmStatic
         fun now() = Moment(Instant.now())
 
+        /**
+         * Returns the amount of minutes between the UTC and the system default time zone.
+         */
+        @JvmStatic
+        fun getSystemOffsetMinutes(): Int {
+            val dateTime = LocalDateTime.now()
```
Comment (a-tze) [inline commons/src/main/java/info/metadude/android/eventfahrplan/commons/temporal/Moment.kt:129]: If I'm using this code on Oct 24th 2020 to look for events happening the next day, it will return incorrect offset (120). Maybe it is okay if only used for scrolling, but to give correct result, "dateTime" must be a parameter to this method instead of using "now".

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java [hunk 2]
```diff
@@ -493,7 +493,11 @@ private void setBell(Session session) {
     private void scrollTo(@NonNull Session session) {
         final ScrollView parent = requireViewByIdCompat(getView(), R.id.scrollView1);
         int height = getNormalizedBoxHeight(getResources(), scale, LOG_TAG);
-        final int pos = (session.relStartTime - conference.getFirstSessionStartsAt()) / 5 * height;
+        int startsAtMinuteUtc = session.relStartTime - conference.getFirstSessionStartsAt();
+        int systemOffsetMinutes = Moment.getSystemOffsetMinutes();
+        // Translate start time minutes from UTC to system time zone rendered to the user.
+        int startsAtMinuteSystem = startsAtMinuteUtc - systemOffsetMinutes;
+        final int pos = startsAtMinuteSystem / 5 * height;
```
Comment (a-tze) [inline app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java:500]: Not sure how the UI and positioning works. More consistent and easy would be to have everything internally as UTC (or datetime with offset, doesnt matter actually) and then convert to "system local" as needed.

So instead of calculating startsAdMinuteUtc I'd rather have the firstSessionStart as absolute UTC datetime and the sessionStart also as datetime. Then you'd get something like a TimeSpan object when subtracting those and take the total minutes from that.

However, the approach in this commit will also work as intended - except for the days that have the actual DST change (this already happened on easterhegg14 or sometime around). But I guess that there will be additional problems with rendering, especially when clock is set back and one hour "appears twice".

Comment (johnjohndoe) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java:500]: I agree that it would be easier to have all calculation wrapped in the `Moment` class. I already added a `TODO` [here](https://github.com/EventFahrplan/EventFahrplan/pull/344/commits/845b25a6d18c53c86993b761dbf9fb6eb6f9ee30) but did not take time to work on it.

Comment (johnjohndoe) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java:500]: I prepared a beginning to encapsulate the calculation in the `Moment` class:

``` java
Moment sessionStartsAtMoment = Moment.ofEpochMilli(session.dateUTC);
Moment firstSessionStartsAtMoment = Moment.ofEpochMilli(conference.getFirstSessionStartsAt());
Moment startsAtMoment = sessionStartsAtMoment.minus(firstSessionStartsAtMoment);
```

I am not sure how to to implement the `minus` function best - here is a draft:

``` kotlin
operator fun minus(moment: Moment): Moment {
    return ofEpochMilli(time.minus(moment.time.toEpochMilli(), ChronoUnit.MILLIS).toEpochMilli())
}
```

When it comes to apply the system time offset I haven't found the Java 8 resp. ThreeTenBp API yet. Any hints are appreciated.

Comment (a-tze) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java:500]: I think it is sufficient to calculate in granularity of minutes, like take the minutes and multiply them with 60.000. 

Regarding the minus, one of the three objects involved probably needs to have another data type. You cannot subtract two datetimes and get a datetime. Either you subtract two datetimes and get a time span, or you subtract a timespan from a datetime and get another datetime.
Maybe you're trapped into having the "startsAtMoment" variable as a moment. Actually what you want there is a plain number of time units that tells you the exact physical duration between the first session and the current session. this can by nature not be a moment, it's either a number of seconds,minutes,whatever or a Timespan (Instant?). So your minus function must not return a moment but just the milliseconds - or even minutes so you dont need to change anything somewhere else. The important thing is only that you have both times "proper" before subtracting them with a proper library - then you get the real number of minutes between them and scrolling (or even rendering a timetable) will be correct.

**Comment by johnjohndoe** [comment]
@a-tze I did not find time to work on a better implementation. Now that the rc3 event is so near I will merge this implementation and leave a `TODO` to refactor this as soon as possible.

**Comment by johnjohndoe** [comment]
@a-tze Still or again broken. See https://github.com/EventFahrplan/EventFahrplan/issues/346#issuecomment-752691184. I will open a new issue later.

**Comment by johnjohndoe** [comment]
@a-tze :new: Bug filed here: #361
