### PR TITLE
Issue 42 - Stay at current scroll position when going back from details

### LINKED ISSUE #42: Stay at current scroll position when going back from event details view
It is really beneficial for the normal user workflow to stay at the current scroll position.

At the moment, the app **always scrolls back to the current time** and the user has to scroll all the way down again.

Many users go through the schedule and try to decide which lectures/talks to go to.

# Enviroment

- Device vendor: Lenovo/ZUK
- Device model: [ZUK Z1](https://www.gsmarena.com/lenovo_zuk_z1-7511.php) (Smartphone)
- Android version: 5.1.1
- Cyanogen version: 12.1-YOG4PAS9IG
- App version: 1.33.1

# How to reproduce
1. Start the app, navigate to the main view (if necessary)
2. Scroll up or down and tap on a talk to see it's details.
3. Tap the back-button.
4. You are now at the current time again, not where you initially scrolled to.

# Also the following Developer Options were customized
- Window Animation Scale: Off
- Transition Animation Scale: Off
- Animation Duration Scale: Off

### PR DESCRIPTION
**Pull request by koelnkalkverbot**
These changes will fix the back navigation issue. I've tested it on several devices and emulator images and it worked well. 
I couldn't find a reason for the duplication of 
``` java
if (MyApp.meta.getNumDays() != 0) {
   // auf jeden Fall reload, wenn mit Lecture ID gestartet
   viewDay(lecture_id != null);
}
```
in `onResume()` in `FahrplanFragment` so I removed one call, as the dupication made it hard to reliably check if we want to scroll to the current time frame or not. Feel free to suggest adjustments.

Resolves #42.

### CODE REVIEW

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java [hunk 1]
```diff
@@ -326,8 +321,11 @@ private void viewDay(boolean reload) {
             int roomIndex = MyApp.roomList.get(i);
             fillRoom(roomView, roomIndex, MyApp.lectureList, boxHeight);
         }
-        scrollToCurrent(mDay, boxHeight);
+        if (MainActivity.getInstance().getScrollToCurrentTimeSlot()) {
+            scrollToCurrent(mDay, boxHeight);
+        }
         updateNavigationMenuSelection();
+        MainActivity.getInstance().resetScrollToCurrentTimeSlot();
```
Comment (johnjohndoe) [inline app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java]: The following code allows to reduce the public interface of `MainActivity` for this use case to a **single** method. The reset is done internally:

``` java
MainActivity.getInstance().shouldScheduleScrollToCurrentTimeSlot(() -> {
    scrollToCurrent(mDay, boxHeight);
    return null;
});
```

in MainActivity.java:

``` java
public void shouldScheduleScrollToCurrentTimeSlot(Function0<Unit> scrollToInstructions) {
    if (shouldScrollToCurrent) {
        scrollToInstructions.invoke();
    }
    shouldScrollToCurrent = true;
}
```

Also, I suggest to change the method name somewhat to let it become easier to understand from the calling side.

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java [hunk 2]
```diff
@@ -73,6 +73,7 @@
 
     private ProgressBar progressBar = null;
     private boolean requiresScheduleReload = false;
+    private boolean scrollToCurrent = true;
```
Comment (johnjohndoe) [inline app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java]: Please rename to `shouldScrollToCurrent` to reflect the boolean type.

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java (hunk 1 above)
Comment (koelnkalkverbot) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java]: Thanks for your quick response. I agree to your suggested changes and already pushed them.

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java (hunk 2 above)
Comment (johnjohndoe) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/MainActivity.java]: Resolved in e47a60b6aca9109824935591c137bd820c8f1158.

File: app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java (hunk 1 above)
Comment (johnjohndoe) [reply app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.java]: Resolved in e47a60b6aca9109824935591c137bd820c8f1158.

**Comment by johnjohndoe** [comment]
@koelnkalkverbot Thanks a lot for your help!
